// 35 minutes
:revealjs_totalTime: 2100

= Type classes

**More than just strategy pattern**

Mateusz Kubuszok

TODO: add stuff from the template

[NOTE.speaker]
--
Preparations:
- open terminal - 1 tab for examples
- arrange them to easily jump from one to another
- put speakers notes on laptop
--

== About me

[%step]
* breaking things in Scala for 8+ years
* breaking things for money for 11 years
* breaking things for fun for 19 years
* a little bit of open source - including co-authoring Chimney for 6 years now
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook

[NOTE.speaker]
--
Every presentation should start with some excuse, why you even are here.
--

== Agenda

[%step]
* TODO

1. example of a good old strategy pattern (to refresh the audience's memory)
2. adding generics to the picture (strategy methods parametrized with generic type, to distinct between implementations intended for different types)
3. letting compiler pass the strategy around (implicits/using/given keywords in Scala)
4. extension methods make strategy usage feel more natural
5. definition of a type class
6. case class + sealed trait/enum (Scala's blessed data types)
7. showing how implementations can be generated out of implementations for primitives + rules for combining implementations (Show type class generated with Magnolia)
8. examples of libraries which generate implementations this way: JSON codecs, config parsers, args parsers, data/type mappers...
9. summary
10. optional bonus if there will be enough time - showing how type classes can be used to define a whole application's architecture (tagless final)

[NOTE.speaker]
--

--

== Strategy pattern

[%step]
[source, scala]
----
trait Discount {
  def apply(price: Int): Int
}

def applyDiscounts(
    item: Item, // case class Item(name: String, price: Int)
    quantity: Int,
    discount: Option[Discount]
): (Int, Int) = {
  val price = item.price * quantity
  val discounted = discount.fold(price)(_.apply(price))
  (price, discounted)
}
----

[%step]
- algorithm extracts dynamic logic to an interface
- we provide instance of that interface as an argument

[NOTE.speaker]
--
Show ``bat example_1_strategy/\*``.
Run ``scala-cli run example_1_strategy`` as an example.

Mention that this is super generic, but if we understand the mechanism, we can use that understanding in the next example.
--

== Strategy with generics

[%step]
[source, scala]
----
trait Show[A] {
  def show(a: A): String
}

def show[A](value: A)(show: Show[A]): String =
  show.show(value)
----

[%step]
[source, scala]
----
val tpe: Tpe
val shoeTpe: Show[Tpe] = value => s"Tpe(${value.field})" // SAM

show(tpe)(showTpe)
----

[NOTE.speaker]
--
This example is not meant to be practical. It is meant to be obvious what it does.
It let us define generic algorithm and then force usage of a strategy matching the type of value.

Explain single abstract method.

Show ``bat example_2_strategy_but_typed/\*``.
Run ``scala-cli run example_2_strategy_but_typed`` as an example.

Compare ``toString`` to ``show``.

Mention that this way we can provide implementation for final classes which we cannot modify.

Mention that it looks kinda boilerplate'y, so let's address that.
--

== Implicits and extension methods

[%step]
[source, scala]
----
trait Show[A] {
  def show(a: A): String
}

extension [A](value: A)
  def show(using show: Show[A]): String = show.show(value)
----

[%step]
[source, scala]
----
val tpe: Tpe
given showTpe: Show[Tpe] = value => s"Tpe(${value.field})"

tpe.show // showTpe is passed for us
----

[%step]
[source, scala]
----
val tpe: Tpe
given Show[Tpe] = value => s"Tpe(${value.field})"

tpe.show // anonymous Show[Tpe] is passed for us
----

[NOTE.speaker]
--
Explain extension method syntax.

Explain that ``using`` is kinda special.

Explain that ``given`` would wire value to using.

Explain that this DI is based on types and value marked as implicit in the scope.

Show ``bat example_3_extensions_implicits/\*``.
Run ``scala-cli run example_3_extensions_implicits`` as an example.

Mention, that we have enough information to tell what a type class is.
--

== Type Class

[%step]
* strategy pattern
* with type parameters (generics)
* where the algorithm often run as an extension method
* and the strategy is passed with type-based DI

[NOTE.speaker]
--
"How we can understand type classes on JVM?"

Remind that it doesn't look like a strategy anymore, but it works the same way - there is an object which defines behavior and it is being passed into algorithm (extension method).

Mention, that Haskellers would not agree with that definition, but they are not the audience if this talk.

In Scala type class is actually a class.

Ask if you would find it mundate to always provide implementation by hand.
--

== Generating implementation from smaller blocks

[%step]
[source, scala]
----
given Show[String] = str => '"' + str + '"'
given Show[Int] = int => int.toString

given [A](using A: Show[A]): Show[Array[A]] = arr =>
  s"Array(${arr.map(_.show).mkString(", ")})"

given [A, B](using A: Show[A], B: Show[B]): Show[(A, B)] = {
  case (a, b) =>
    s"Tuple2(${a.show}, ${b.show})"
}
----

[NOTE.speaker]
--
Explain that we can use smaller blocks to build a bigger blocks when it comes to implicits.

Show ``bat example_4_tuples_arrays/\*``.
Run ``scala-cli run example_4_tuples_arrays`` as an example.

Mention that we shouldn't limit ourselves to just tuples and that providing code for each arity would be tireing.
--

== Type class derivation

[%step]
Generating a type class for some type using:

[%step]
- type classes for its components (record's fields, subtypes)
- some logic how to combine/dispatch to components' type classes

[NOTE.speaker]
--
Mention that this is basically a code generation, but one that matches some existing interface.

Mention that it is best undetstood by example.

Show ``bat example_5_derivation/\*``.
Run ``scala-cli run example_5_derivation`` as an example.
--

=== !

Tools for performing type class derivation:

[%step]
- Shapeless library
- Mirrors (Scala 3 only)
- Magnolia library
- macros

[NOTE.speaker]
--
Mention that we won't delve into details how to use these tools as they are mostly used by librarys' authors, and instead we would show some real world examples.

Because we aren't interested just in academic overcomplicated way of producing strings.
--

== Examples of type class based solutions

[%step]
- JSON serialization
- config parsing
- type mapping
- Swagger schema generation (TODO)

[NOTE.speaker]
--
Mention that we don't want to limit ourselves to just JSON because Java devs already know Jackson.

Show ``bat example_6_real_world_example/\*``.
Run ``scala-cli run example_6_real_world_example`` as an example.
--

== Summary

TODO

== Questions?

== Thank You!

TODO: add QR code with "rate me"
