// 35 minutes
:revealjs_totalTime: 2100

= Type classes

**More than just strategy pattern**

Mateusz Kubuszok

[NOTE.speaker]
--
Preparations:
- (on Mac): enable workspaces to share 1 screen constantly
- open terminal - 1 tab for examples
- increase terminal font size to 40pt
- arrange them to easily jump from one to another
- put speakers notes on laptop
--

== About me

[%step]
* breaking things in Scala for 8+ years
* breaking things for money for 11 years
* breaking things for fun for 19 years
* a little bit of open source - including co-authoring Chimney for 6 years now
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook

[NOTE.speaker]
--
Every presentation should start with some excuse, why you even are here.
--

== Agenda

[%step]
* what is is a strategy
* how to get from strategy pattern to type class pattern
* code generation
* some real world example

[NOTE.speaker]
--

--

== Strategy pattern

[%step]
[source, scala]
----
trait DiscountStrategy {
  def apply(price: Int): Int
}

def applyDiscounts(
    item: Item, // case class Item(name: String, price: Int)
    quantity: Int,
    discount: Option[DiscountStrategy]
): (Int, Int) = {
  val price = item.price * quantity
  val discounted = discount.fold(price)(_.apply(price))
  (price, discounted)
}
----

[%step]
- algorithm extracts dynamic logic to an interface
- we provide instance of that interface as an argument

[NOTE.speaker]
--
Show ``bat example_1_strategy/\*``.
Run ``scala-cli run example_1_strategy`` as an example.

Mention that this is super generic, but if we understand the mechanism, we can use that understanding in the next example.
--

== Strategy with generics

[%step]
[source, scala]
----
// in Java it would be:
// interface Show<A> { ... }
trait Show[A] {
  def show(a: A): String
}

def show[A](value: A)(show: Show[A]): String =
  show.show(value)
----

[%step]
[source, scala]
----
class Example(val fiels: String)

val example: Example = new Example("test")

val showExample: Show[Example] =
  // Single Abstract Method syntax:
  // creates new Show[Example] { ... }
  // as if it was a function
  value => s"Example(${value.field})"

show(example)(showExample)
----

[NOTE.speaker]
--
This example is not meant to be practical. It is meant to be obvious what it does.
It let us define generic algorithm and then force usage of a strategy matching the type of value.

Explain single abstract method.

Show ``bat example_2_strategy_but_typed/\*``.
Run ``scala-cli run example_2_strategy_but_typed`` as an example.

Compare ``toString`` to ``show``.

Mention that this way we can provide implementation for ``final`` classes which we cannot modify.

Mention that it helps us implement Open-Closed principle from SOLID - we can add/change functionality without modifying the existing algorithm.

Mention that it looks kinda boilerplate'y, so let's address that.
--

== Implicits and extension methods

[%step]
[source, scala]
----
trait Show[A] {
  def show(a: A): String
}

extension [A](value: A)
  def show(using show: Show[A]): String = show.show(value)
----

[%step]
[source, scala]
----
class Example(val fiels: String)
val example: Example = new Example("test")

given showExample: Show[Example] =
  value => s"Example(${value.field})"

example.show(using showExample)
----

[%step]
[source, scala]
----
example.show // showExample is passed for us
----

[%step]
[source, scala]
----
given Show[Example] =
  value => s"Example(${value.field})"

example.show // anonymous Show[Example] is passed for us
----

[NOTE.speaker]
--
Explain extension method syntax.

Explain that ``using`` is kinda special.

Explain that ``given`` would wire value to using.

Explain that this DI is based on types and value marked as implicit in the scope.

Show ``bat example_3_extensions_implicits/\*``.
Run ``scala-cli run example_3_extensions_implicits`` as an example.

Mention, that we have enough information to tell what a type class is.
--

== Type Class

[%step]
* strategy pattern
* with type parameters (generics)
* where the algorithm often run as an extension method
* and the strategy is passed with type-based DI

[NOTE.speaker]
--
"How we can understand type classes on JVM?"

Remind that it doesn't look like a strategy anymore, but it works the same way - there is an object which defines behavior and it is being passed into algorithm (extension method).

Mention, that Haskellers would not agree with that definition, but they are not the audience if this talk.

In Scala type class is actually a class.

Ask if you would find it mundate to always provide implementation by hand.
--

== Generating implementation from smaller blocks

[%step]
[source, scala]
----
given Show[String] = str => '"' + str + '"'
given Show[Int] = int => int.toString

given [A](using A: Show[A]): Show[Array[A]] = arr =>
  s"Array(${arr.map(_.show).mkString(", ")})"

given [A, B](using A: Show[A], B: Show[B]): Show[(A, B)] = {
  case (a, b) =>
    s"Tuple2(${a.show}, ${b.show})"
}
----

[NOTE.speaker]
--
Explain that we can use smaller blocks to build a bigger blocks when it comes to implicits.

Show ``bat example_4_tuples_arrays/\*``.
Run ``scala-cli run example_4_tuples_arrays`` as an example.

Mention that we shouldn't limit ourselves to just tuples and that providing code for each arity would be tireing.
--

== Type class derivation

[%step]
Generating a type class for some type using:

[%step]
- type classes for its components (record's fields, subtypes)
- some logic how to combine/dispatch to components' type classes

[NOTE.speaker]
--
Mention that this is basically a code generation, but one that matches some existing interface.

Mention that it is best undetstood by example.

Show ``bat example_5_derivation/\*``.
Run ``scala-cli run example_5_derivation`` as an example.
--

== Examples of type-class-based solutions

[%step]
- JSON serialization
- config parsing
- type mapping

[NOTE.speaker]
--
Mention that we don't want to limit ourselves to just JSON because Java devs already know Jackson.

Show ``bat example_6_real_world_example/\*``.
Run ``scala-cli run example_6_real_world_example`` as an example.

Commands - run them in a separate tab:

1. ``curl -XGET http://localhost:8080/memos/my-secret-memo/?passwd=bad-pass``
2. ``curl -XGET http://localhost:8080/memos/my-secret-memo/?passwd=secret-pass``
3. ``curl -XPUT 'http://localhost:8080/memos/my-secret-memo/?passwd=secret-pass' -d '{ "content": "My note's content", "name": "My Secret Note" }'``
4. ``curl -XGET http://localhost:8080/memos/my-secret-memo/?passwd=secret-pass``
--

== Summary

[%step]
- (on JVM) type class can be understood as a strategy patter
- with a (type-based) dependency injection
- and a code generation
- slides and examples available on my GitHub profile https://github.com/MateuszKubuszok/[GitHub.com/MateuszKubuszok]

== Questions?

== Thank You!
